---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:example:role
rules:
  - apiGroups:
      - extensions
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - psp.example
    verbs:
      - use
